//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBFirstDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class CategoryImages
    {
        public int CategoryId { get; set; }
        public int ImageId { get; set; }
        public int TypeImage { get; set; }
    
        public virtual Images Images { get; set; }
        public virtual Categories Categories { get; set; }
    }
}
