//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBFirstDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class GlobalOption
    {
        public int Id { get; set; }
        public string StringKey { get; set; }
        public string OptionContent { get; set; }
        public string DescriptionKey { get; set; }
        public bool IsHtml { get; set; }
    }
}
