//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBFirstDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class PointOnImgs
    {
        public int Id { get; set; }
        public int CoordX { get; set; }
        public int CoordY { get; set; }
        public int BannerId { get; set; }
    
        public virtual BannerWithPoints BannerWithPoints { get; set; }
    }
}
