//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBFirstDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Review
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Content { get; set; }
        public int ProductId { get; set; }
        public int Rating { get; set; }
        public System.DateTime DateCreation { get; set; }
        public bool IsRead { get; set; }
        public bool IsApproved { get; set; }
    
        public virtual Products Products { get; set; }
    }
}
