//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBFirstDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class VideoGuide
    {
        public int Id { get; set; }
        public string SrcVideoThumbnail { get; set; }
        public string LinkYouTobe { get; set; }
        public Nullable<int> HomeEntityId { get; set; }
    
        public virtual HomeEntity HomeEntity { get; set; }
    }
}
